### ISSUE TITLE
TOTP not accepted - PHP Warning:  Undefined array key "type" in user.inc.php on line 364

### ISSUE THREAD

**Issue by strk** [simpleid/simpleid#115]
### Description

Since a few days (weeks?) my TOTP are not accepted by the server, which always tells me "The verification code is not correct."

### Steps to reproduce

Steps to reproduce the behaviour:
1. Enter username/password (success)
2. Enter TOTP
3. See error or unexpected result

### Expected behaviour

The OTP works

### Logs

Not much in simpleid.log, just:

> 2024-07-02 15:16:41 UTC bbb [INFO] Session opened for "login" from xxx [yyy, zzz]
> 2024-07-02 15:16:41 UTC bbb [DEBUG] extension_invoke_all: ui_routes

Something possibly interesting in webserver logs:

> PHP Warning:  Undefined array key "type" in user.inc.php on line 364

### Environment

 - Version 1.0.6 from https://simpleid.org/releases/simpleid-1.0.6/
 - SimpleID modules/extensions loaded: sreg,ui
 - Server OS: Debian 12 (bookworm)
 - PHP: 8.2.20
 - Browser: Firefox

**Comment by strk** [comment]
I did run the upgrade and am having the same issue

**Comment by kelvinmo** [comment]
Firstly, try resetting TOTP by following the instructions here: https://simpleid.org/docs/1/common-problems/#otp

If that doesn't work, try deleting `<your user name>.usrstore` in the store directory of the SimpleID installation.  Note that this will also remove all your saved preferences.

**Comment by strk** [comment]
Still didn't work after removing the usrstore file in the store directory, disabling OTP and re-creating OTP.
I don't get the PHP warning anymore though, just:

> The verification code is not correct.

The journal log entries have a weird prefix (but not all of them) like this:
```
2024-07-04 03:47:06 UTC 1bfbi8hneo2pgtve1dnog1co2s [DEBUG] extension_invoke_all: ui_routes
2024-07-04 03:47:21 UTC  [DEBUG] user_init
2024-07-04 03:47:21 UTC 1bfbi8hneo2pgtve1dnog1co2s [INFO] Session opened for "login" from 79b3f82b36c9002c852d97562eccd952 [<ip>,<ip>]
2024-07-04 03:47:21 UTC 1bfbi8hneo2pgtve1dnog1co2s [DEBUG] extension_invoke_all: ui_routes
```

Does that give any hint ?

**Comment by strk** [comment]
The "funny" thing is that when I disable/enable TOTP and I'm asked to enter the OTP to verify I got the QR code right, it works. So this is surely NOT an issue with time

**Comment by kelvinmo** [comment]
The prefix (`1bfbi8hneo2pgtve1dnog1co2s`) is the PHP session ID - so it can be ignored.

The only thing I can think of is how PHP 8.2 may interfere with passed-by-reference parameter in `user_verify_otp` (https://github.com/simpleid/simpleid/blob/2b8720aec9748ed6970237b7428d3fa074e9e77c/www/user.inc.php#L363)

**Comment by kelvinmo** [comment]
Sadly I am unable to replicate on php 8.2.21 on caddy

**Comment by kelvinmo** [comment]
The only thing I can think of is that the OTP key isn't saved properly in the usrstore file.  (The initial setup process where you enable and verify the OTP doesn't read from or write to the usrstore file until it's completed.)

You may wish to check whether the usrstore file and its parent directory is writable by the web server user.  In addition, you can open the usrstore file with a text editor and search for `s:3:"otp"` to see if the OTP key is actually saved.  The file is simply the output of the PHP `serialize` function so you should be able to decode it plainly.  (Don't post the contents of the file here as it contains the OTP key.)

**Comment by strk** [comment]
I haven't had a chance yet to try the suggested solution

**Comment by strk** [comment]
Stale bot seems to be failing at removing the stale label upon my commenting

**Comment by strk** [comment]
After disabling OTP again and re-enabling it things seem to work. Thanks.
