### ISSUE TITLE
Problems setting up SimpleID2: `Invalid token [/simpleid/www/vendor/tuupola/branca/src/Branca.php:159]`

### ISSUE THREAD

**Issue by cresh** [simpleid/simpleid#123]
I am trying to set up a new SimpleID 2 installation with Docker. I am using PHP-FPM 8.3 & Nginx 1.26 on Alpine Linux 3.20. I've installed SimpleID 2 via composer and set it up by following https://simpleid.org/docs/2/installing/ .

Trying it out by opening my installation with the browser fails with:

```
Internal Server Error
Invalid token [/simpleid/www/vendor/tuupola/branca/src/Branca.php:159]
```

Here is the error in the log:

```
NOTICE: PHP message: Invalid token [/simpleid/www/vendor/tuupola/branca/src/Branca.php:159]
NOTICE: PHP message: [core/Util/SecureString.php:66] Branca\Branca->decode()
NOTICE: PHP message: [core/Util/SecureString.php:101] SimpleID\Util\SecureString->toPlaintext()
NOTICE: PHP message: [core/Util/OpaqueIdentifier.php:111] SimpleID\Util\SecureString::getPlaintext()
NOTICE: PHP message: [core/Util/OpaqueIdentifier.php:43] SimpleID\Util\OpaqueIdentifier::getOpaqueToken()
NOTICE: PHP message: [core/Auth/AuthManager.php:439] SimpleID\Util\OpaqueIdentifier->__construct()
NOTICE: PHP message: [core/Auth/RememberMeAuthSchemeModule.php:47] SimpleID\Auth\AuthManager->getCookieName()
NOTICE: PHP message: [core/ModuleManager.php:63] SimpleID\Auth\RememberMeAuthSchemeModule->__construct()
NOTICE: PHP message: [index.php:31] SimpleID\ModuleManager->loadModule()
2024/12/03 06:55:05 [error] 44#44: *1 FastCGI sent in stderr: "PHP message: Invalid token [/simpleid/www/vendor/tuupola/branca/src/Branca.php:159]; PHP message: [core/Util/SecureString.php:66] Branca\Branca->decode(); PHP message: [core/Util/SecureString.php:101] SimpleID\Util\SecureString->toPlaintext(); PHP message: [core/Util/OpaqueIdentifier.php:111] SimpleID\Util\SecureString::getPlaintext(); PHP message: [core/Util/OpaqueIdentifier.php:43] SimpleID\Util\OpaqueIdentifier::getOpaqueToken(); PHP message: [core/Auth/AuthManager.php:439] SimpleID\Util\OpaqueIdentifier->__construct(); PHP message: [core/Auth/RememberMeAuthSchemeModule.php:47] SimpleID\Auth\AuthManager->getCookieName(); PHP message: [core/ModuleManager.php:63] SimpleID\Auth\RememberMeAuthSchemeModule->__construct(); PHP message: [index.php:31] SimpleID\ModuleManager->loadModule()" while reading response header from upstream, client: 10.20.0.31, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:"
```

It looks like SimpleID tries to decode a Cookie and fails. But there is no Cookie yet, since SimpleID did not work yet and could not have set one (I've verified that with the browser's developer console).

Do you have any tips what I could be missing?
Do you have an idea what is going wrong here?

**Comment by kelvinmo** [comment]
The issue isn't related to the lack of a cookie.

It's related to the process that SimpleID uses to generate the name of the cookie.  SimpleID uses a salt to generate cookie names so that they are unique to each installation.  The salt itself is encrypted at rest when stored on the server.  The error is occurring because for whatever reason the salt cannot be decrypted from its encrypted value.

A couple of ways to diagnose this issue:

1. Firstly, check `config.php` to ensure that `secure_secret` or `secure_secret_file` (or the equivalent environment variables) is set correctly.  The values of these variables cannot change.
2. Try renaming the `opaque-token.setting` file in the store directory to another name to see if it resolves the issue.  (A new `opaque-token.setting` file should be automatically generated.)

**Comment by cresh** [comment]
Thank you very much for the fast reply!

I have set `secure_secret` in `config.php` to a 64 character long string.

When I delete `cache/*` and `store/*` and then refresh my browser, I can see the login window:

<img width="1610" alt="Screenshot 2024-12-03 at 13 21 50" src="https://github.com/user-attachments/assets/58bbcf5e-f5d8-440c-911c-2a80fbb97635">

When I then refresh my browser again, I see:

<img width="603" alt="Screenshot 2024-12-03 at 13 21 58" src="https://github.com/user-attachments/assets/26c2b404-cc42-4192-8b8c-c7f7d1c69b73">

with this backtrace in the logs:

```
10.20.0.31 - - [03/Dec/2024:12:25:46 +0000] "GET / HTTP/1.1" 200 1707 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "2a02:8070:8984:1c80:288f:8a01:adc8:caba" 0.013 0.013 . -
NOTICE: PHP message: Key must be exactly 24 bytes [/simpleid/www/vendor/tuupola/branca/src/Branca.php:73]
NOTICE: PHP message: [core/Util/SecurityToken.php:75] Branca\Branca->__construct()
NOTICE: PHP message: [core/Auth/AuthModule.php:268] SimpleID\Util\SecurityToken->__construct()
NOTICE: PHP message: [core/Base/IndexModule.php:69] SimpleID\Auth\AuthModule->loginForm()
NOTICE: PHP message: [index.php:39] Base->run()
2024/12/03 12:25:51 [error] 44#44: *37 FastCGI sent in stderr: "PHP message: Key must be exactly 24 bytes [/simpleid/www/vendor/tuupola/branca/src/Branca.php:73]; PHP message: [core/Util/SecurityToken.php:75] Branca\Branca->__construct(); PHP message: [core/Auth/AuthModule.php:268] SimpleID\Util\SecurityToken->__construct(); PHP message: [core/Base/IndexModule.php:69] SimpleID\Auth\AuthModule->loginForm(); PHP message: [index.php:39] Base->run()" while reading response header from upstream, client: 10.20.0.31, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:"
10.20.0.31 - - [03/Dec/2024:12:25:51 +0000] "GET / HTTP/1.1" 500 194 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "2a02:8070:8984:1c80:288f:8a01:adc8:caba" 0.008 0.007 . -
```

**Comment by kelvinmo** [comment]
I have managed to replicate the error. It appears that there may be an issue with an upstream library (Branca) which I will need more time to diagnose.

**Comment by kelvinmo** [comment]
Would you please advise the version of PHP you are using?

**Comment by cresh** [comment]
Sure, thanks for your help!

```
# php --version
PHP 8.3.14 (cli) (built: Nov 21 2024 08:27:36) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.14, Copyright (c), by Zend Technologies
# php-fpm83 --version
PHP 8.3.14 (fpm-fcgi) (built: Nov 21 2024 08:27:36)
Copyright (c) The PHP Group
Zend Engine v4.3.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.14, Copyright (c), by Zend Technologies
```

**Comment by kelvinmo** [comment]
Can you please check whether 782a899 fixes the issue.

**Comment by cresh** [comment]
Yes, this fixes the issue, thank you!

The next problem I hit I could fix with https://github.com/simpleid/simpleid/pull/124 .

Now after login I see:

<img width="532" alt="Screenshot 2024-12-04 at 13 39 59" src="https://github.com/user-attachments/assets/47e0590c-88c3-491b-8447-7255d682ae7f">
