### ISSUE TITLE
"Remember me" not working

### ISSUE THREAD

**Issue by kelvinmo** [simpleid/simpleid#19]
This issue was migrated from SimpleID trac [164]

People contributed to the original ticket: @cweiske, @kelvinmo

---

After logging into SimpleID 1.0.2 and activating the "Remember me on this computer for two weeks." checkbox, I keep being logged out after one or two days.

The setup instructions do not say anything specifically about PHP's session settings, but I guess that it could be that normal PHP sessions are cleaned up after 1 day, making the session invalid or so.

What can I do to debug this problem?

---

_Comment from_: @kelvinmo
_Date_: `Aug 06 2017`

It's been a long time since I've touched the 1.x codebase...

The "remember me" feature is called `cookieauth` and `autologin` in the code.  You'll find the functions dealing with this in `user.inc.php`.

When the user authenticates successfully, `_user_login` checks whether the autologin checkbox in the login page is checked, and if so, calls `user_cookieauth_create_cookie()`.  `user_cookieauth_create_cookie` then stores the authentication information on the server and generates a separate cookie for the browser.

This cookie gets invalidated (in `user_cookieauth_user_auto_login()`) if any of the following occurs:

- new installation of SimpleID (`get_form_token()` and `simpleid_cookie_name()` will return different values)
- authentication information deleted from the server cache
- browser presents the autologin cookie, but the cookie does not match the server version
- different browser is used

**Comment by sokai** [comment]
FYI: 1.0.3 works
