### ISSUE TITLE
Put configuration into its own directory

### ISSUE THREAD

**Issue by Tyil** [simpleid/simpleid#23]
I'm trying to build a Docker image for SimpleID so I can easily integrate it with my current infra. It would be helpful if the configuration file could live in it's own configuration directory, so this can be mapped into the Docker container.

If you want, I can supply a patch for it.

**Comment by tribut** [comment]
Couldn't you just create a symlink to the new config directory in the startup-script and then mount that?

    mkdir -p "$CONFIGDIR"
    mv config.inc.php "$CONFIGDIR"
    ln -s "$CONFIGDIR/config.inc.php"

**Comment by Tyil** [comment]
> I'm not an expert on Docker, but are you able to mount a single file as a volume, as in -v /local/config.inc.php:/simpleid/www/config.inc.php?

You could, but then you enter into areas where https://github.com/docker/compose/issues/2127 comes in to play. I want to use Docker to make it simpler, not more of an issue. I'd rather do it properly.

> Couldn't you just create a symlink to the new config directory in the startup-script and then mount that?

I guess that could work, but this sounds like a workaround to something that can be easily fixed in the first place.

Let me phrase it differently. Is there a reason the configuration is *required to be in the root directory*? This is a questionable approach to manage your configuration files, and I'd like to see this improved to play better with other systems.

**Comment by kelvinmo** [comment]
The main driver for having the configuration file where it is now is history.  The SimpleID codebase is more than 10 years old now, and at the time putting the configuration file in the same directory as the webroot is the simplest solution (it's *Simple*ID after all).

One way to solve this is to look for the configuration file in multiple places.

**Comment by Tyil** [comment]
That would work for me.
