### ISSUE TITLE
Client ID and client secret

### ISSUE THREAD

**Issue by agentcobra** [simpleid/simpleid#24]
Hi,
How to generate client ID and client secret ?
I doesn't found anythink in documentation.

I would like to connect worpdress website and kandoard website to simpleid

----
https://fr.wordpress.org/plugins/single-sign-on-client/
https://github.com/kanboard/plugin-oauth2#2-configure-the-provider-in-kanboard

**Comment by kelvinmo** [comment]
A client ID can be anything you want, as long as it is a valid file name.

A client secret must be long and random, and should be generated using a secure password generator.

**Comment by agentcobra** [comment]
redirect doesn't work :confused:
