### ISSUE TITLE
session_set_cookie_params(): CookieLifetime cannot be negative

### ISSUE THREAD

**Issue by Tyil** [simpleid/simpleid#25]
I'm trying to run `simpleid` on my server. The server running `simpleid` is a Docker container with Apache, using the following `Dockerfile`:

```
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -qq
RUN apt install -y apache2 php7.2
RUN apt install -y php7.2-bcmath php7.2-mbstring php7.2-zip php7.2-xml
RUN apt install -y composer

# Add repository

EXPOSE 80

# Instead, run a shell wrapper to also update deps and shit
CMD apachectl -e info -DFOREGROUND

# vim: ft=dockerfile
```

I've ran `composer install --no-dev` to get the dependencies, copied the `config.php.dist` and updated the `canonical_base_path` to my own domain.

The server is running, but reports the following error when trying to load a page:

```
[Tue May 01 19:21:07.688710 2018] [php7:notice] [pid 14] [client 172.18.1.7:36312] session_set_cookie_params(): CookieLifetime cannot be negative
```

**Comment by kelvinmo** [comment]
This is due to a change in handling of cookie functions in PHP 7.2.  If you downgrade to an earlier version of PHP it should work.

**Comment by kelvinmo** [comment]
You may also like to try changing the following line in composer.json

```json
 "bcosca/fatfree-core": "3.5.*",
```

to 

```json
 "bcosca/fatfree-core": "3.6.*",
```

and see if it works.
