### ISSUE TITLE
Add support for OpenID Connect

### ISSUE THREAD

**Issue by filips123** [simpleid/simpleid#26]
Add support for OpenID Connect.
OpenID Connect 1.0 is a simple identity layer on top of the OAuth 2.0 protocol. It allows Clients to verify the identity of the End-User based on the authentication performed by an Authorization Server, as well as to obtain basic profile information about the End-User in an interoperable and REST-like manner.
More info on http://openid.net/connect/

**Comment by kelvinmo** [comment]
The version of SimpleID on the master branch supports OpenID Connect.
