### ISSUE TITLE
SimpleID 2 how to proceed after install step 6

### ISSUE THREAD

**Issue by petrk94** [simpleid/simpleid#31]
Hello,

I have made the installation try to get run SimpleID 2 with code of the git repository. But now I stuck in the problem how to proceed with webfingers?
http://simpleid.koinic.net/docs/2/installing/#webfinger

Where the Webfinger files has to be located? Where is the /.well-known/ directory, this is not understandable from the instructions.

Please fix/help

Thanks

**Comment by kelvinmo** [comment]
webfinger is only required if you are using the OpenID Connect protocol.  If you are using the old and deprecated OpenID protocol does not require webfinger, as it uses a separate discovery protocol.

The webfinger protocol requires two things:

1. a webfinger server that maps `mailto` and `acct` URIs to the OpenID Connect server---SimpleID 2 has a very simple [webfinger server](http://simpleid.koinic.net/docs/2/webfinger/) included
2. the webfinger server to be accessible from the well-known URL `/.well-known/webfinger`, meaning that the server has to be installed at that URL, or a redirect set up on the web server to redirect that URL to the webfinger server

**Comment by petrk94** [comment]
@kelvinmo ok and where is the webfinger server exactly? What I have to configure and how?
I have the whole installation for the test on simpleid2.xxxxx.de
What I have to change in which path/directory?

**Comment by kelvinmo** [comment]
The webfinger server is enabled by default, at the URL `<simpleid root>/.well-known/webfinger`.  However, you will need to create a redirect on your web server to reach it.

For example, if you want to use SimpleID for account URIs such as `mailto:user@example.com` or `acct:user@example.com`, the webfinger URL would be `https://example.com/.well-known/webfinger` (i.e. the host name, plus `/.well-known/webfinger`.  If you have installed SimpleID on `https://simpleid.example.com` you will need to create a redirect from `https://example.com/.well-known/webfinger` to `https://simpleid.example.com/.well-known/webfinger`

See the [documentation](http://simpleid.koinic.net/docs/2/webfinger/) for more details.

**Comment by petrk94** [comment]
@kelvinmo I will check it out and come back again
