### ISSUE TITLE
Support for OAuth

### ISSUE THREAD

**Issue by filips123** [simpleid/simpleid#33]
Is OAuth (2) supported in SimpleID?
There are some places in the code which refer to OAuth, but in the documentation it is nothing.

**Comment by kelvinmo** [comment]
OAuth 2 is supported in the version currently on git.  Please note that this is a complete rewrite compared to SimpleID 1.  For more information see https://simpleid.org/docs/2/

**Comment by filips123** [comment]
Yes but documentation for it is not published.

**Comment by kelvinmo** [comment]
I think I now understand what you mean.

SimpleID supports OAuth 2 via [OpenID Connect](https://simpleid.org/docs/2/openid-connect/), which operates on top of OAuth to provide identity services.  If you want OAuth to open up your API while providing authentication against your identity service, you will need to implement that yourself using the many OAuth server libraries available.

**Comment by filips123** [comment]
Could this be added to documentation?
