### ISSUE TITLE
Cannot redeclare random_bytes()

### ISSUE THREAD

**Issue by strk** [simpleid/simpleid#34]
PHP7 introduced a [core random_bytes function](https://www.php.net/manual/en/function.random-bytes.php) so the one in simpleid/www/random.inc triggers this error:
```
Cannot redeclare random_bytes()
```

Sounds like an easy fix. Do you accep PRs against a 1.0 branch ?

**Comment by strk** [comment]
Well it looks like latest version (1.0.2) does not have this problem.
My problem was with the latest package included in Debian repositories (up to Debian 9)!
It would be nice to get updated packages, but this ticket is now invalid

**Comment by kelvinmo** [comment]
My understanding is that the Debian package (which I don't maintain) has been abandoned.

**Comment by strk** [comment]
Here's the debian package source, if anyone wants to pick it up: https://salsa.debian.org/auth-team/simpleid
