### ISSUE TITLE
HTTP 404 (POST auth/login/)

### ISSUE THREAD

**Issue by jorsn** [simpleid/simpleid#36]
My `config.php` –  and my `.htaccess`: https://gist.github.com/jorsn/d724decfbdf69290c36fc2f53e9364fb.

When I install SimpleID 2 with the instructions from https://simpleid.org/docs/2/installing/, I get a HTTP 404 (POST auth/login/) error, as soon a s I try to login (directly after login submit button). The log displays no errors.

The SimpleID tree resides under /var/www/virtual/jorsn/simpleid.uber.space, which is symlinked to  /var/www/virtual/jorsn/html/simpleid.

**Comment by kelvinmo** [comment]
Please check whether 3fb9370 fixes the issue.

**Comment by kelvinmo** [comment]
Further fixes (to an unrelated issue) in e582861

**Comment by jorsn** [comment]
After the second fix it works!
