### ISSUE TITLE
Base::offsetset() is not compatible with PHP 8.1 (and probably 8.0).

### ISSUE THREAD

**Issue by dertuxmalwieder** [simpleid/simpleid#54]
I tried migrating from SimpleID 1.0.3 to SimpleID 2 using `composer` and the `simpleid-tool`. I got a config file and an identity file (and I set a new password). However, when I try to log in from a website which has my OpenID data, I am greeted with a `Fatal Error`:

    Fatal error: Return type of Base::offsetset($key, $val) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Temporarily enabling PHP 8.0 leads to this error instead:

    Undefined array key "public_jwks_file"

As I think PHP 8.1 support is more interesting, I'd still focus on the first part ... :-)

**Environment:**
 - Server OS: CentOS 7
 - PHP: 8.1.2
 - Browser: Vivaldi

**Comment by kelvinmo** [comment]
This appears to be related to an upstream issue (bcosca/fatfree#1241), for which a PR has been created at bcosca/fatfree-core#332.  Once that has been merged into upstream the issue should hopefully go away

**Comment by ikkez** [comment]
Problems solved in latest fatfree-core release.

**Comment by kelvinmo** [comment]
Created PR #61 to pull from upstream, as well as implementing other compatibility changes
