### ISSUE TITLE
Missing $security_message

### ISSUE THREAD

**Issue by kAlvaro** [simpleid/simpleid#55]
**Description**

If you enable `allow_autocomplete`, all you see when you point the browser to the main page is an unresolved templating variable:

> Undefined variable $security_message

![imagen](https://user-images.githubusercontent.com/1327350/151039467-673b6212-9c66-4d4a-8608-e069bfa6d409.png)

**Steps to reproduce**

Steps to reproduce the behaviour:

1. Copy `www/config.php.dist` as `www/config.php` and tweak accordingly.
2. Set `'allow_autocomplete' => true,`

**Expected behaviour**

See login form as in SimpleID/1.0.3

**Logs**

Log directory remains empty.

**Environment:**
 - Version: dev-master
 - SimpleID modules/extensions loaded: default ones
 - Server OS: Windows 10 Home (developer machine)
 - PHP: PHP/8.0.14
 - Browser: Firefox/96.0.2

**Expected behaviour**

I'm not familiar with project code but the only reference to `security_message` I could find is in the HTML template that loads it:

```
<check if="{{ @@security_class }}" >
<div class="login-security {{ @security_class }}">
    <p>{{ @security_message | raw }}</p>
</div>
</check>
```

I guess a string should be defined at `en.ini` and passed to the view at `www/core/Auth/AuthModule.php`:

```php
            case AuthManager::MODE_REENTER_CREDENTIALS:
                // Follow through
                $this->f3->set('uid', $form_state['uid']);
            case AuthManager::MODE_CREDENTIALS:
                $security_class = ($config['allow_autocomplete']) ? 'allow-autocomplete ' : '';
                $this->f3->set('security_class', $security_class);

                $this->f3->set('submit_button', $this->f3->get('intl.common.login'));
                $this->f3->set('title', $this->f3->get('intl.common.login'));
                break;
```

**Comment by kelvinmo** [comment]
This issue relates some old SimpleID 1.x code that weren't removed properly in dev-master.  This is fixed in #56
